namespace AssetInventory.HttpConnectivity;
internal enum Currency
{
	AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL,
	BSD, BTN, BWP, BYN, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP,
	ERN, ETB, EUR, FJD, FKP, FOK, GBP, GEL, GGP, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF,
	IDR, ILS, IMP, INR, IQD, IRR, ISK, JEP, JMD, JOD, JPY, KES, KGS, KHR, KID, KMF, KRW, KWD, KYD, KZT,
	LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR, MWK, MXN, MYR, MZN,
	NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR,
	SBD, SCR, SDG, SEK, SGD, SHP, SLE, SOS, SRD, SSP, STN, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD,
	TVD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VES, VND, VUV, WST, XAF, XCD, XDR, XOF, XPF, YER, ZAR, ZMW,
	ZWL
}

internal record CurrencyInfo(string CurrencyCode, string CurrencyName, string CountryName)
{
	public static readonly IReadOnlyDictionary<string, CurrencyInfo> CurrencyData = new Dictionary<string, CurrencyInfo>()
	{
		{"AED",new("AED", "UAE Dirham",                     "United Arab Emirates")},
		{"AFN",new("AFN", "Afghan Afghani",                 "Afghanistan")},
		{"ALL",new("ALL", "Albanian Lek",                   "Albania")},
		{"AMD",new("AMD", "Armenian Dram",                  "Armenia")},
		{"ANG",new("ANG", "Netherlands Antillian Guilder",  "Netherlands Antilles")},
		{"AOA",new("AOA", "Angolan Kwanza",                 "Angola")},
		{"ARS",new("ARS", "Argentine Peso",                 "Argentina")},
		{"AUD",new("AUD", "Australian Dollar",              "Australia")},
		{"AWG",new("AWG", "Aruban Florin",                  "Aruba")},
		{"AZN",new("AZN", "Azerbaijani Manat",              "Azerbaijan")},
		{"BAM",new("BAM", "Bosnia and Herzegovina Mark",    "Bosnia and Herzegovina")},
		{"BBD",new("BBD", "Barbados Dollar",                "Barbados")},
		{"BDT",new("BDT", "Bangladeshi Taka",               "Bangladesh")},
		{"BGN",new("BGN", "Bulgarian Lev",                  "Bulgaria")},
		{"BHD",new("BHD", "Bahraini Dinar",                 "Bahrain")},
		{"BIF",new("BIF", "Burundian Franc",                "Burundi")},
		{"BMD",new("BMD", "Bermudian Dollar",               "Bermuda")},
		{"BND",new("BND", "Brunei Dollar",                  "Brunei")},
		{"BOB",new("BOB", "Bolivian Boliviano",             "Bolivia")},
		{"BRL",new("BRL", "Brazilian Real",                 "Brazil")},
		{"BSD",new("BSD", "Bahamian Dollar",                "Bahamas")},
		{"BTN",new("BTN", "Bhutanese Ngultrum",             "Bhutan")},
		{"BWP",new("BWP", "Botswana Pula",                  "Botswana")},
		{"BYN",new("BYN", "Belarusian Ruble",               "Belarus")},
		{"BZD",new("BZD", "Belize Dollar",                  "Belize")},
		{"CAD",new("CAD", "Canadian Dollar",                "Canada")},
		{"CDF",new("CDF", "Congolese Franc",                "Democratic Republic of the Congo")},
		{"CHF",new("CHF", "Swiss Franc",                    "Switzerland")},
		{"CLP",new("CLP", "Chilean Peso",                   "Chile")},
		{"CNY",new("CNY", "Chinese Renminbi",               "China")},
		{"COP",new("COP", "Colombian Peso",                 "Colombia")},
		{"CRC",new("CRC", "Costa Rican Colon",              "Costa Rica")},
		{"CUP",new("CUP", "Cuban Peso",                     "Cuba")},
		{"CVE",new("CVE", "Cape Verdean Escudo",            "Cape Verde")},
		{"CZK",new("CZK", "Czech Koruna",                   "Czech Republic")},
		{"DJF",new("DJF", "Djiboutian Franc",               "Djibouti")},
		{"DKK",new("DKK", "Danish Krone",                   "Denmark")},
		{"DOP",new("DOP", "Dominican Peso",                 "Dominican Republic")},
		{"DZD",new("DZD", "Algerian Dinar",                 "Algeria")},
		{"EGP",new("EGP", "Egyptian Pound",                 "Egypt")},
		{"ERN",new("ERN", "Eritrean Nakfa",                 "Eritrea")},
		{"ETB",new("ETB", "Ethiopian Birr",                 "Ethiopia")},
		{"EUR",new("EUR", "Euro",                           "European Union")},
		{"FJD",new("FJD", "Fiji Dollar",                    "Fiji")},
		{"FKP",new("FKP", "Falkland Islands Pound",         "Falkland Islands")},
		{"FOK",new("FOK", "Faroese Króna",                  "Faroe Islands")},
		{"GBP",new("GBP", "Pound Sterling",                 "United Kingdom")},
		{"GEL",new("GEL", "Georgian Lari",                  "Georgia")},
		{"GGP",new("GGP", "Guernsey Pound",                 "Guernsey")},
		{"GHS",new("GHS", "Ghanaian Cedi",                  "Ghana")},
		{"GIP",new("GIP", "Gibraltar Pound",                "Gibraltar")},
		{"GMD",new("GMD", "Gambian Dalasi",                 "The Gambia")},
		{"GNF",new("GNF", "Guinean Franc",                  "Guinea")},
		{"GTQ",new("GTQ", "Guatemalan Quetzal",             "Guatemala")},
		{"GYD",new("GYD", "Guyanese Dollar",                "Guyana")},
		{"HKD",new("HKD", "Hong Kong Dollar",               "Hong Kong")},
		{"HNL",new("HNL", "Honduran Lempira",               "Honduras")},
		{"HRK",new("HRK", "Croatian Kuna",                  "Croatia")},
		{"HTG",new("HTG", "Haitian Gourde",                 "Haiti")},
		{"HUF",new("HUF", "Hungarian Forint",               "Hungary")},
		{"IDR",new("IDR", "Indonesian Rupiah",              "Indonesia")},
		{"ILS",new("ILS", "Israeli New Shekel",             "Israel")},
		{"IMP",new("IMP", "Manx Pound",                     "Isle of Man")},
		{"INR",new("INR", "Indian Rupee",                   "India")},
		{"IQD",new("IQD", "Iraqi Dinar",                    "Iraq")},
		{"IRR",new("IRR", "Iranian Rial",                   "Iran")},
		{"ISK",new("ISK", "Icelandic Króna",                "Iceland")},
		{"JEP",new("JEP", "Jersey Pound",                   "Jersey")},
		{"JMD",new("JMD", "Jamaican Dollar",                "Jamaica")},
		{"JOD",new("JOD", "Jordanian Dinar",                "Jordan")},
		{"JPY",new("JPY", "Japanese Yen",                   "Japan")},
		{"KES",new("KES", "Kenyan Shilling",                "Kenya")},
		{"KGS",new("KGS", "Kyrgyzstani Som",                "Kyrgyzstan")},
		{"KHR",new("KHR", "Cambodian Riel",                 "Cambodia")},
		{"KID",new("KID", "Kiribati Dollar",                "Kiribati")},
		{"KMF",new("KMF", "Comorian Franc",                 "Comoros")},
		{"KRW",new("KRW", "South Korean Won",               "South Korea")},
		{"KWD",new("KWD", "Kuwaiti Dinar",                  "Kuwait")},
		{"KYD",new("KYD", "Cayman Islands Dollar",          "Cayman Islands")},
		{"KZT",new("KZT", "Kazakhstani Tenge",              "Kazakhstan")},
		{"LAK",new("LAK", "Lao Kip",                        "Laos")},
		{"LBP",new("LBP", "Lebanese Pound",                 "Lebanon")},
		{"LKR",new("LKR", "Sri Lanka Rupee",                "Sri Lanka")},
		{"LRD",new("LRD", "Liberian Dollar",                "Liberia")},
		{"LSL",new("LSL", "Lesotho Loti",                   "Lesotho")},
		{"LYD",new("LYD", "Libyan Dinar",                   "Libya")},
		{"MAD",new("MAD", "Moroccan Dirham",                "Morocco")},
		{"MDL",new("MDL", "Moldovan Leu",                   "Moldova")},
		{"MGA",new("MGA", "Malagasy Ariary",                "Madagascar")},
		{"MKD",new("MKD", "Macedonian Denar",               "North Macedonia")},
		{"MMK",new("MMK", "Burmese Kyat",                   "Myanmar")},
		{"MNT",new("MNT", "Mongolian Tögrög",               "Mongolia")},
		{"MOP",new("MOP", "Macanese Pataca",                "Macau")},
		{"MRU",new("MRU", "Mauritanian Ouguiya",            "Mauritania")},
		{"MUR",new("MUR", "Mauritian Rupee",                "Mauritius")},
		{"MVR",new("MVR", "Maldivian Rufiyaa",              "Maldives")},
		{"MWK",new("MWK", "Malawian Kwacha",                "Malawi")},
		{"MXN",new("MXN", "Mexican Peso",                   "Mexico")},
		{"MYR",new("MYR", "Malaysian Ringgit",              "Malaysia")},
		{"MZN",new("MZN", "Mozambican Metical",             "Mozambique")},
		{"NAD",new("NAD", "Namibian Dollar",                "Namibia")},
		{"NGN",new("NGN", "Nigerian Naira",                 "Nigeria")},
		{"NIO",new("NIO", "Nicaraguan Córdoba",             "Nicaragua")},
		{"NOK",new("NOK", "Norwegian Krone",                "Norway")},
		{"NPR",new("NPR", "Nepalese Rupee",                 "Nepal")},
		{"NZD",new("NZD", "New Zealand Dollar",             "New Zealand")},
		{"OMR",new("OMR", "Omani Rial",                     "Oman")},
		{"PAB",new("PAB", "Panamanian Balboa",              "Panama")},
		{"PEN",new("PEN", "Peruvian Sol",                   "Peru")},
		{"PGK",new("PGK", "Papua New Guinean Kina",         "Papua New Guinea")},
		{"PHP",new("PHP", "Philippine Peso",                "Philippines")},
		{"PKR",new("PKR", "Pakistani Rupee",                "Pakistan")},
		{"PLN",new("PLN", "Polish Złoty",                   "Poland")},
		{"PYG",new("PYG", "Paraguayan Guaraní",             "Paraguay")},
		{"QAR",new("QAR", "Qatari Riyal",                   "Qatar")},
		{"RON",new("RON", "Romanian Leu",                   "Romania")},
		{"RSD",new("RSD", "Serbian Dinar",                  "Serbia")},
		{"RUB",new("RUB", "Russian Ruble",                  "Russia")},
		{"RWF",new("RWF", "Rwandan Franc",                  "Rwanda")},
		{"SAR",new("SAR", "Saudi Riyal",                    "Saudi Arabia")},
		{"SBD",new("SBD", "Solomon Islands Dollar",         "Solomon Islands")},
		{"SCR",new("SCR", "Seychellois Rupee",              "Seychelles")},
		{"SDG",new("SDG", "Sudanese Pound",                 "Sudan")},
		{"SEK",new("SEK", "Swedish Krona",                  "Sweden")},
		{"SGD",new("SGD", "Singapore Dollar",               "Singapore")},
		{"SHP",new("SHP", "Saint Helena Pound",             "Saint Helena")},
		{"SLE",new("SLE", "Sierra Leonean Leone",           "Sierra Leone")},
		{"SOS",new("SOS", "Somali Shilling",                "Somalia")},
		{"SRD",new("SRD", "Surinamese Dollar",              "Suriname")},
		{"SSP",new("SSP", "South Sudanese Pound",           "South Sudan")},
		{"STN",new("STN", "São Tomé and Príncipe Dobra",    "São Tomé and Príncipe")},
		{"SYP",new("SYP", "Syrian Pound",                   "Syria")},
		{"SZL",new("SZL", "Eswatini Lilangeni",             "Eswatini")},
		{"THB",new("THB", "Thai Baht",                      "Thailand")},
		{"TJS",new("TJS", "Tajikistani Somoni",             "Tajikistan")},
		{"TMT",new("TMT", "Turkmenistan Manat",             "Turkmenistan")},
		{"TND",new("TND", "Tunisian Dinar",                 "Tunisia")},
		{"TOP",new("TOP", "Tongan Paʻanga",                 "Tonga")},
		{"TRY",new("TRY", "Turkish Lira",                   "Turkey")},
		{"TTD",new("TTD", "Trinidad and Tobago Dollar",     "Trinidad and Tobago")},
		{"TVD",new("TVD", "Tuvaluan Dollar",                "Tuvalu")},
		{"TWD",new("TWD", "New Taiwan Dollar",              "Taiwan")},
		{"TZS",new("TZS", "Tanzanian Shilling",             "Tanzania")},
		{"UAH",new("UAH", "Ukrainian Hryvnia",              "Ukraine")},
		{"UGX",new("UGX", "Ugandan Shilling",               "Uganda")},
		{"USD",new("USD", "United States Dollar",           "United States")},
		{"UYU",new("UYU", "Uruguayan Peso",                 "Uruguay")},
		{"UZS",new("UZS", "Uzbekistani So'm",               "Uzbekistan")},
		{"VES",new("VES", "Venezuelan Bolívar Soberano",    "Venezuela")},
		{"VND",new("VND", "Vietnamese Đồng",                "Vietnam")},
		{"VUV",new("VUV", "Vanuatu Vatu",                   "Vanuatu")},
		{"WST",new("WST", "Samoan Tālā",                    "Samoa")},
		{"XAF",new("XAF", "Central African CFA Franc",      "CEMAC")},
		{"XCD",new("XCD", "East Caribbean Dollar",          "Organisation of Eastern Caribbean States")},
		{"XDR",new("XDR", "Special Drawing Rights",         "International Monetary Fund")},
		{"XOF",new("XOF", "West African CFA franc",         "CFA")},
		{"XPF",new("XPF", "CFP Franc",                      "Collectivités d'Outre-Mer")},
		{"YER",new("YER", "Yemeni Rial",                    "Yemen")},
		{"ZAR",new("ZAR", "South African Rand",             "South Africa")},
		{"ZMW",new("ZMW", "Zambian Kwacha",                 "Zambia")},
		{"ZWL",new("ZWL", "Zimbabwean Dollar",              "Zimbabwe")},
	};
}